let mix = require('laravel-mix');
require('mix-html-builder');
require('laravel-mix-replace-in-file');
const fs = require('fs-extra');

const THEME_PATH = "./content/themes/" + process.env.MIX_THEME_SLUG
const ASSETS_PATH = THEME_PATH + "/assets";
const SOURCE_PATH = "./src"

mix.options({
    uglify: true,
});
mix.disableNotifications();

mix.version([ASSETS_PATH + '/css/style.min.css', ASSETS_PATH + '/js/script.min.js']);
mix.setPublicPath(THEME_PATH);
mix.sass(SOURCE_PATH + '/scss/app.scss', ASSETS_PATH + '/css/style.min.css')
    .options({
        processCssUrls: false
    }).js(SOURCE_PATH + '/js/base.js', ASSETS_PATH + '/js/script.min.js')
    .autoload({
        jquery: ['$', 'window.jQuery', 'jQuery']
    });

//Build HTML
mix.html({
    htmlRoot: SOURCE_PATH + '/pages/**/*.php',
    output: '.',
    minify: {
        collapseBooleanAttributes: mix.inProduction(),
        collapseWhitespace: mix.inProduction(),
        removeAttributeQuotes: mix.inProduction(),
        minifyJS: mix.inProduction(),
        minifyCSS: mix.inProduction(),
        removeComments: mix.inProduction(),
        ignoreCustomFragments: [/<\/body>/, /<\/html>/, /<\/div>/, /<%[\s\S]*?%>/, /<\?[\s\S]*?\?>/],
        includeAutoGeneratedTags: false
    },
})
    .copy(SOURCE_PATH + '/style.css', THEME_PATH + '/style.css')
    .replaceInFile({
        files: THEME_PATH + '/style.css',
        from: /##NAME##/g,
        to: process.env.MIX_THEME_NAME,
    })
    .copy(SOURCE_PATH + '/inc', THEME_PATH + '/inc')
    .copy(SOURCE_PATH + '/*.php', THEME_PATH) + '/*.php';

mix.then(() => {
    //Copy files
    fs.copySync(SOURCE_PATH + '/mailers', THEME_PATH + '/mailers')
    fs.copySync(SOURCE_PATH + '/plugins', THEME_PATH + '/plugins')
    fs.copySync(SOURCE_PATH + '/imgs', ASSETS_PATH + '/imgs')
    fs.copySync(SOURCE_PATH + '/fonts', ASSETS_PATH + '/fonts')
    // Keep SVG partials untouched by HTML minifier (prevents malformed <path> output).
    fs.copySync(SOURCE_PATH + '/pages/partials', THEME_PATH + '/partials')
    fs.copySync(SOURCE_PATH + '/screenshot.png', THEME_PATH + '/screenshot.png');
});
